os: osx
osx_image: xcode9
language: swift
cache:
  directories:
  - $HOME/DnA/ML\ Model
before_install:
        - brew update && brew install git-lfs
        - git lfs install
before_script: 
        - git lfs pull
script:
  - xcodebuild -scheme DnA -project DnA.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.0' build

